# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 The Linux Foundation and contributors
"""Tests for the tracked-subsystem registry.

Real files on disk rather than stubs, because what this module does *is*
read files somebody else writes -- korgalore's conf.d and lei's saved
searches -- and a fake of those would only pin our idea of their shape.
The samples here are copied from a live container.

The thing most worth pinning is the failure that would not look like one:
a subsystem name that does not resolve has to raise, because silently
searching three subsystems when four were asked for comes back as a
short, confident, wrong answer.
"""

from pathlib import Path
from typing import Optional

import pytest

from subsystems import KINDS, Store, Subsystem, Subsystems

PAGE_CACHE = """\
# Auto-generated by: kgl track-subsystem 'PAGE CACHE'
# Generated: 2026-09-17T17:02:49+00:00
# Query date range: d:90.days.ago..

[subsystem]
name = 'PAGE CACHE'

[feeds.page_cache-mailinglist]
url = 'lei:{base}/page_cache-mailinglist'

[feeds.page_cache-patches]
url = 'lei:{base}/page_cache-patches'

[deliveries.page_cache-patches]
feed = 'page_cache-patches'
target = 'local'
labels = []
"""

# A subsystem name with a slash and mixed case in it, which is not an edge
# case at all -- MAINTAINERS is full of them.
LSILOGIC = """\
[subsystem]
name = 'LSILOGIC/SYMBIOS/NCR 53C8XX and 53C1010 PCI-SCSI drivers'

[feeds.lsilogic-mailinglist]
url = 'lei:{base}/lsilogic-mailinglist'
"""

SAVED_SEARCH = """\
[lei]
\tq = {query}
[lei "q"]
\tonly = https://lore.kernel.org/all/
\tlocal = 0
\toutput = v2:{base}/{archive}
[external "https://lore.kernel.org/all/"]
\tlastresult = 1789676585
"""


@pytest.fixture
def tracked(tmp_path: Path) -> Subsystems:
    """A container tracking two subsystems, one of them mailinglist-only."""
    conf_d = tmp_path / 'conf.d'
    conf_d.mkdir()
    base = tmp_path / 'lei'
    base.mkdir()
    (conf_d / 'page_cache.toml').write_text(PAGE_CACHE.format(base=base))
    (conf_d / 'lsilogic.toml').write_text(LSILOGIC.format(base=base))
    return Subsystems(conf_d=conf_d, saved_searches=tmp_path / 'saved-searches')


def under(where: Optional[Path]) -> Path:
    """The registry's two directories are Optional -- a container that tracks
    nothing has neither -- and the fixture here always sets both."""
    assert where is not None
    return where


def found(registry: Subsystems, name: str) -> Subsystem:
    """find() is Optional because a name may be untracked; a test that just
    looked one up is asserting it is there, so say that once, here."""
    subsystem = registry.find(name)
    assert subsystem is not None, f'{name} is not tracked'
    return subsystem


def stored(registry: Subsystems, name: str, kind: str) -> Store:
    """The same, one level down: a subsystem need not have every kind."""
    store = found(registry, name).store(kind)
    assert store is not None, f'{name} has no {kind} archive'
    return store


def saved(registry: Subsystems, base: Path, archive: str, query: str) -> None:
    """Write the saved search lei would have created for one archive."""
    where = under(registry.saved_searches) / f'{archive}-abc123'
    where.mkdir(parents=True, exist_ok=True)
    (where / 'lei.saved-search').write_text(SAVED_SEARCH.format(query=query, base=base, archive=archive))


# --- reading what korgalore wrote --------------------------------------


def test_a_tracked_subsystem_is_found_under_the_name_maintainers_gives_it(tracked: Subsystems) -> None:
    assert 'PAGE CACHE' in tracked.names()


def test_a_subsystem_keeps_both_of_its_archives(tracked: Subsystems) -> None:
    page_cache = found(tracked, 'PAGE CACHE')
    assert page_cache.kinds == ('patches', 'mailinglist')


def test_the_archives_are_listed_narrowest_first(tracked: Subsystems) -> None:
    """patches before mailinglist, so an unqualified ask reads the specific one first."""
    assert [store.kind for store in found(tracked, 'PAGE CACHE').stores] == list(KINDS)


def test_a_subsystem_may_have_only_one_kind(tracked: Subsystems) -> None:
    """kgl can generate either feed alone, and half a config is not an error."""
    assert found(tracked, 'lsilogic').kinds == ('mailinglist',)


def test_a_file_that_is_not_a_subsystem_is_left_alone(tracked: Subsystems, tmp_path: Path) -> None:
    """conf.d holds korgalore's subscriptions too; only subsystems belong here."""
    (under(tracked.conf_d) / 'sub-something.toml').write_text("[feeds.something]\nurl = 'lei:/tmp/x'\n")
    assert tracked.names() == (
        'LSILOGIC/SYMBIOS/NCR 53C8XX and 53C1010 PCI-SCSI drivers',
        'PAGE CACHE',
    )


def test_an_unreadable_config_does_not_take_the_others_with_it(tracked: Subsystems) -> None:
    (under(tracked.conf_d) / 'broken.toml').write_text('this is not [ toml')
    assert 'PAGE CACHE' in tracked.names()


def test_a_container_with_nothing_tracked_says_so_rather_than_failing(tmp_path: Path) -> None:
    assert Subsystems(conf_d=tmp_path / 'absent').all() == ()


# --- provenance --------------------------------------------------------


def test_an_archive_carries_the_query_that_fills_it(tracked: Subsystems, tmp_path: Path) -> None:
    saved(tracked, tmp_path / 'lei', 'page_cache-patches', '(dfn:mm/filemap.c) AND d:90.days.ago..')
    store = stored(tracked, 'PAGE CACHE', 'patches')
    assert store.to_dict()['built_from'] == '(dfn:mm/filemap.c) AND d:90.days.ago..'


def test_an_archive_with_no_saved_search_simply_does_not_claim_one(tracked: Subsystems) -> None:
    assert 'built_from' not in stored(tracked, 'PAGE CACHE', 'patches').to_dict()


def test_an_archive_korgalore_has_not_filled_yet_says_it_is_absent(tracked: Subsystems) -> None:
    """Tracked but empty is ordinary: the directory appears with the first message."""
    assert stored(tracked, 'PAGE CACHE', 'patches').to_dict()['present'] is False


def test_an_archive_that_exists_says_so(tracked: Subsystems) -> None:
    stored(tracked, 'PAGE CACHE', 'patches').path.mkdir(parents=True)
    assert stored(tracked, 'PAGE CACHE', 'patches').present is True


# --- resolving ---------------------------------------------------------


def test_a_name_resolves_however_it_was_typed(tracked: Subsystems) -> None:
    assert found(tracked, 'page   cache').name == 'PAGE CACHE'


def test_the_key_korgalore_filed_it_under_resolves_too(tracked: Subsystems) -> None:
    """Results and filenames both show the key; either should get an answer."""
    assert found(tracked, 'page_cache').name == 'PAGE CACHE'


def test_resolving_one_subsystem_gives_every_archive_it_has(tracked: Subsystems) -> None:
    assert [store.kind for store in tracked.resolve(['PAGE CACHE'])] == ['patches', 'mailinglist']


def test_a_kind_narrows_to_that_one_archive(tracked: Subsystems) -> None:
    found = tracked.resolve(['PAGE CACHE'], ['mailinglist'])
    assert [store.name for store in found] == ['page_cache-mailinglist']


def test_several_subsystems_resolve_to_all_of_their_archives(tracked: Subsystems) -> None:
    found = tracked.resolve(['PAGE CACHE', 'lsilogic'], ['mailinglist'])
    assert len(found) == 2


def test_an_untracked_subsystem_is_refused_not_quietly_dropped(tracked: Subsystems) -> None:
    """The wrong answer here is a short answer that looks complete."""
    with pytest.raises(ValueError) as caught:
        tracked.resolve(['PAGE CACHE', 'XARRAY'])
    assert 'XARRAY' in str(caught.value)


def test_being_refused_tells_the_caller_what_it_could_have_asked_for(tracked: Subsystems) -> None:
    with pytest.raises(ValueError) as caught:
        tracked.resolve(['NFSD'])
    assert 'PAGE CACHE' in str(caught.value)


def test_a_kind_the_subsystem_does_not_have_is_an_explanation(tracked: Subsystems) -> None:
    with pytest.raises(ValueError) as caught:
        tracked.resolve(['lsilogic'], ['patches'])
    assert 'patches' in str(caught.value)


def test_a_kind_nobody_has_heard_of_is_refused(tracked: Subsystems) -> None:
    with pytest.raises(ValueError) as caught:
        tracked.resolve(['PAGE CACHE'], ['bugs'])
    assert 'bugs' in str(caught.value)


def test_nothing_tracked_is_explained_rather_than_blamed_on_the_name(tmp_path: Path) -> None:
    with pytest.raises(ValueError) as caught:
        Subsystems(conf_d=tmp_path / 'absent').resolve(['PAGE CACHE'])
    assert 'not tracking any subsystems' in str(caught.value)


# --- the listing -------------------------------------------------------


def test_the_listing_explains_what_the_two_kinds_can_answer(tracked: Subsystems) -> None:
    """The kinds differ in what they can find at all, so the caveat travels."""
    note = tracked.to_dict()['note']
    assert 'bug report carries no diff' in note and 'list-scoped' in note


def test_the_listing_counts_what_is_tracked(tracked: Subsystems) -> None:
    assert tracked.to_dict()['count'] == 2


def test_reading_the_config_again_does_not_reread_the_disk(tracked: Subsystems) -> None:
    tracked.all()
    (under(tracked.conf_d) / 'xarray.toml').write_text("[subsystem]\nname = 'XARRAY'\n")
    assert 'XARRAY' not in tracked.names()


def test_the_cache_lets_go_so_a_newly_tracked_subsystem_turns_up(tracked: Subsystems) -> None:
    tracked.ttl = 0
    tracked.all()
    (under(tracked.conf_d) / 'xarray.toml').write_text("[subsystem]\nname = 'XARRAY'\n")
    assert 'XARRAY' in tracked.names()


def test_an_archive_names_itself_the_way_lei_and_korgalore_both_spell_it(tmp_path: Path) -> None:
    store = Store(subsystem='PAGE CACHE', key='page_cache', kind='patches', path=tmp_path)
    assert store.name == 'page_cache-patches'
